"""INIT

Revision ID: 38b4b03e44f6
Revises:
Create Date: 2025-09-03 09:54:34.549097

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "38b4b03e44f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
