"""add type Subscription

Revision ID: d3cd6ec604e8
Revises: 656b64e75eb7
Create Date: 2025-11-12 21:00:26.651997

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3cd6ec604e8"
down_revision: Union[str, Sequence[str], None] = "656b64e75eb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_type = sa.Enum(
        "TRIAL", "STANDARD", "PREMIUM", name="subscription_type"
    )
    subscription_type.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "subscriptions",
        sa.Column(
            "type",
            sa.Enum("TRIAL", "STANDARD", "PREMIUM", name="subscription_type"),
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "has_used_trial", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "has_used_trial")
    op.drop_column("subscriptions", "type")
    op.execute("DROP TYPE IF EXISTS subscription_type;")
    # ### end Alembic commands ###
