"""Referral add

Revision ID: 599a5cb412fc
Revises: 6a0357aa804b
Create Date: 2026-01-01 21:36:27.644031

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "599a5cb412fc"
down_revision: Union[str, Sequence[str], None] = "6a0357aa804b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("inviter_id", sa.Integer(), nullable=False),
        sa.Column("invited_id", sa.Integer(), nullable=False),
        sa.Column("bonus_given", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("bonus_given_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["invited_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["inviter_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invited_id", name="uq_referrals_invited"),
    )
    op.create_index(
        op.f("ix_referrals_invited_id"), "referrals", ["invited_id"], unique=False
    )
    op.create_index(
        op.f("ix_referrals_inviter_id"), "referrals", ["inviter_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referrals_inviter_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_invited_id"), table_name="referrals")
    op.drop_table("referrals")
    # ### end Alembic commands ###
