"""изменил связь подписок один ко многим

Revision ID: 6a0357aa804b
Revises: ed80f61c6720
Create Date: 2025-12-09 10:04:16.801883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a0357aa804b"
down_revision: Union[str, Sequence[str], None] = "ed80f61c6720"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("subscriptions_user_id_key"), "subscriptions", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("subscriptions_user_id_key"),
        "subscriptions",
        ["user_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
