"""update model KnowledgeChancs

Revision ID: 8093bfaf3b62
Revises: 93b4a66b7d75
Create Date: 2026-03-11 15:15:59.516469

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8093bfaf3b62"
down_revision: Union[str, Sequence[str], None] = "93b4a66b7d75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledgechunks",
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_knowledgechunks_source"), "knowledgechunks", ["source"], unique=False
    )
    op.create_index(
        "knowledge_chunk_embedding_idx",
        "knowledgechunks",
        ["embedding"],
        unique=False,
        postgresql_using="ivfflat",
        postgresql_with={"lists": 10},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "knowledge_chunk_embedding_idx",
        table_name="knowledgechunks",
        postgresql_using="ivfflat",
        postgresql_with={"lists": 10},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_knowledgechunks_source"), table_name="knowledgechunks")
    op.drop_column("knowledgechunks", "meta")
    # ### end Alembic commands ###
