"""init new LLM 256

Revision ID: 93b4a66b7d75
Revises: c34257df953f
Create Date: 2026-03-05 14:47:49.466567

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "93b4a66b7d75"
down_revision: Union[str, Sequence[str], None] = "c34257df953f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "knowledgechunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=256),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "knowledgechunks",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=256),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
