"""add new subscription type

Revision ID: c017a8b8370f
Revises: d89bff5480a2
Create Date: 2026-04-29 22:09:21.710413

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c017a8b8370f"
down_revision: Union[str, Sequence[str], None] = "d89bff5480a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE subscription_type ADD VALUE 'FOUNDER'")
    op.execute("ALTER TYPE subscription_type ADD VALUE 'ULTIMATE'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
