"""add status vpn_config

Revision ID: d89bff5480a2
Revises: aafcdbaa2c5b
Create Date: 2026-04-06 23:47:11.942040

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d89bff5480a2"
down_revision: Union[str, Sequence[str], None] = "aafcdbaa2c5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    vpn_status_enum = postgresql.ENUM(
        "ACTIVE", "PENDING_DELETE", "DELETED", name="vpn_config_status"
    )
    vpn_status_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledgechunks_source"), table_name="knowledgechunks")
    op.drop_index(
        op.f("knowledge_chunk_embedding_idx"),
        table_name="knowledgechunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "10"},
        postgresql_using="ivfflat",
    )
    op.drop_table("knowledgechunks")
    op.add_column(
        "vpnconfigs",
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PENDING_DELETE", "DELETED", name="vpn_config_status"),
            nullable=True,  # сначала nullable=True
            server_default="ACTIVE",
        ),
    )
    op.execute("UPDATE vpnconfigs SET status = 'ACTIVE' WHERE status IS NULL")

    # делаем колонку NOT NULL
    op.alter_column("vpnconfigs", "status", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vpnconfigs", "status")
    vpn_status_enum = postgresql.ENUM(
        "ACTIVE", "PENDING_DELETE", "DELETED", name="vpn_config_status"
    )
    vpn_status_enum.drop(op.get_bind())
    op.create_table(
        "knowledgechunks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "meta",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("knowledgechunks_pkey")),
    )
    op.create_index(
        op.f("knowledge_chunk_embedding_idx"),
        "knowledgechunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"lists": "10"},
        postgresql_using="ivfflat",
    )
    op.create_index(
        op.f("ix_knowledgechunks_source"), "knowledgechunks", ["source"], unique=False
    )
    # ### end Alembic commands ###
